### ISSUE TITLE
Avoid duplication using modify-babel-preset

### ISSUE THREAD

**Issue by developit** [Araphel/babel-preset-es2015-native-modules#1]
Hiya. This preset aggregates a large number of plugins which need to be kept in sync with `babel-preset-es2015`, but it is done manually.  This can be cumbersome to maintain, particularly with Babel's fairly rapid pace of development and release.

I maintain a module called [`modify-babel-preset`](https://github.com/developit/modify-babel-preset) that automates the job of mutating existing presets, so you can express `babel-preset-es2015` as a `dependency` or `peerDependency`, and then simply provide a list of operations to perform on that preset in order to turn it into `babel-preset-es2015-native-modules`.

Using `modify-babel-preset` would simplify this preset down to the following:

```js
var modify = require('modify-babel-preset');

module.exports = modify('es2015', {
    // remove the commonjs plugin
    'transform-es2015-modules-commonjs': false
});
```

Just thought I'd drop the note. Cheers!

**Comment by Bartekus** [comment]
Cool, thanks for sharing, this is mainly used for Webpack's treeshaking functionality so aside from that I don't find much use to modify the remaining babel-presets, but I'll keep this open for open people's reference. Thanks again for heads up, I'm sure there will be use and need for it.
