### ISSUE TITLE
Missing "transform-es2015-duplicate-keys" in preset?

### ISSUE THREAD

**Issue by OshotOkill** [Araphel/babel-preset-es2015-native-modules#2]
![missing](https://cloud.githubusercontent.com/assets/6079112/13552229/eeb31764-e394-11e5-8447-8f017c3b4cdf.png)

It seems not only `transform-es2015-modules-commonjs` but also `transform-es2015-duplicate-keys` was removed from the `babel-preset-es2015`

**Comment by Bartekus** [comment]
Or perhaps transform-es2015-duplicate-keys was recently added ;)
Either way, I've corrected this problem by adding the missing transform and I've also bumped the version of few other transforms, so it should be all good now.
Thank you for your help in this matter @OshotOkill
