### ISSUE TITLE
spread.js: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by oreqizer** [Araphel/babel-preset-es2015-native-modules#5]
![screen shot 2016-04-28 at 12 51 56](https://cloud.githubusercontent.com/assets/11172408/14883757/518180d6-0d40-11e6-9e4e-30d942104dfd.png)

I get this error when using `es2015-native-modules`. When I fall back to using `es2015` only, it works OK.

My config:
![screen shot 2016-04-28 at 12 55 36](https://cloud.githubusercontent.com/assets/11172408/14883789/89e7cd9a-0d40-11e6-9e44-dde604db722c.png)

You think this may be an issue with imports, my config, or some plugin?

**Comment by Bartekus** [comment]
Despite not knowing the full nature of the error I would personally start by looking into the 'add-module-exports' plugin as its suppose to provide exactly what native-modules are missing, specifically the CommonJS modules support.
