### ISSUE TITLE
Failing to build since 6.9.0 with babel-plugin-transform-es2015-modules-commonjs missing

### ISSUE THREAD

**Issue by stevegibbings** [Araphel/babel-preset-es2015-native-modules#6]
Since moving to 6.9.0 our build is failing with babel-plugin-transform-es2015-modules-commonjs not being found. With the prior 6.6.0 version approach of listing each dependency it works OK.

Any ideas?

Thanks,

Steve.

**Comment by stevegibbings** [comment]
```bash
npm install babel-plugin-transform-es2015-modules-commonjs
```

In the root of my prpject doesn't install the dependencies. If I run npm install in the node_module/babel-preset-es2015-native-modules the dependency is installed and it all works again. I can't work out why this new version would install it's dependencies

**Comment by suchostone** [comment]
Facing same issue. Forced 6.6.0 menawhile..

**Comment by stevegibbings** [comment]
I'm doing the same. I've looked at the code of 6.9.0 but can't see why it fails to install. Will look closer when I have the time.

**Comment by Bartekus** [comment]
Umm the whole point of es2015-native-modules is for them not to have es2015-modules-commonjs.

**Comment by stevegibbings** [comment]
Yes but it's failing in the index.js and doesn't install its own dependencies on install so you have to run npm install in this packages folder. 

There is definitely something wrong here. Can you try a fresh empty project and only run npm install in the root folder. You'll see what we are seeing then. Thanks. I'll assist if I can.

**Comment by Bartekus** [comment]
Indeed, it does seem that it's broken at the moment, and the error 'smart-mirror' is not much of help. I'm investigating.

**Comment by stevegibbings** [comment]
Cool. Please let me know if you would like me to help. I can run tests for you on any pull request you create. Thanks for creating the preset.

**Comment by Bartekus** [comment]
It should be working properly now @stevegibbings, cheers!

**Comment by Bartekus** [comment]
I'll close this issue now, but feel free to reopen it should the problem persist.

**Comment by stevegibbings** [comment]
I'll give it a test today. Thanks for looking at it so quickly.

**Comment by Bartekus** [comment]
Thank you and no problem.

**Comment by stevegibbings** [comment]
Tested 6.9.2 and working great now. Much appreciated
