### ISSUE TITLE
writing webpack config using es6 imports

### ISSUE THREAD

**Issue by tsm91** [Araphel/babel-preset-es2015-native-modules#7]
I checked out webpack 2 tree shaking feature.

`webpack-dev-server --config tools/webpack/webpack.dev.babel.js --hot --inline` wont work, because i think webpack internally uses the `.babelrc` file in the project root which no longer uses `babel-plugin-transform-es2015-modules-commonjs` that is why you cannot write the webpack config file itself using es6 imports.

I solved the problem with this 2 scripts below:

```
"scripts": {
    "webpack-dev-server": "babel-node --presets es2015 ./node_modules/.bin/webpack-dev-server",
    "start": "NODE_ENV=development npm run webpack-dev-server -- --config tools/webpack/webpack.dev.js --hot --inline"
  },
```

the question is, is there any better way to solve this problem?

webpack version: 2.1.0-beta.20
node version: 6.3.1

**Comment by Bartekus** [comment]
Hey @tsm91 sorry for the delay, but as far as the babel and .babelrc file goes, it takes precedence over anything else so from the root of the directory where it is present, down to it's children, and all the way down until the next .babelrc file everything will be governed by it's settings.
Also you can transpile the webpack config written in es6 to es5 with babel just prior to starting webpack so there is that as well as executing it using babel-node, tho that option is definitely slower and not production safe.

In either way, I'll close this ticket for now but feel free to reopen it should there be anything else related to this issue that you'd like to ask or add to.
Cheers!
