### ISSUE TITLE
Babel natively supports this now

### ISSUE THREAD

**Issue by avindra** [Araphel/babel-preset-es2015-native-modules#8]
Check this most recent change:

https://github.com/babel/babel/blob/master/CHANGELOG.md#loose-and-modules-options-for-babel-preset-es2015-3331-3627

I think you should updated this package to use : 

```js
{
  presets: [
    ["es2015", { "modules": false }]
  ]
}
```

And encourage other users to do the same on the readme. What do you say?

**Comment by Bartekus** [comment]
That's pretty interesting, perhaps this would be the perfect solution:
```
// for loose and native modules
{
  presets: [
    ["es2015", { "loose": true, "modules": false }]
  ]
}
```

**Comment by avindra** [comment]
I'm honestly not sure if turning on loose mode would be a good idea, even after reading this article:

http://www.2ality.com/2015/12/babel6-loose-mode.html

**Comment by Bartekus** [comment]
Yeah after looking at what Alex had to say about loose mode I agree with you about it not being a good idea at all here. That being said, I'll roll-out the new version with:
```
{
  presets: [
    ["es2015", { "modules": false }]
  ]
}

```
implemented.

**Comment by taion** [comment]
You should deprecate this package actually – the recommended approach now is for users to directly use the preset with options, to have more flexibility in e.g. not having to pull down yet another npm dependency just to add loose mode.

**Comment by kdex** [comment]
Wouldn't the above configuration also break ES2015 modules for stuff that currently still needs to transpile modules? E.g. consider `gulpfile.babel.js`, `webpack.config.babel.js`, …

**Comment by Bartekus** [comment]
@avindra & @taion thank you gentlemen for the heads up and recommendation as per which I've deprecated this package in favour of the proper implementation.
This package will now return
```
{
  presets: [
    ["es2015", { "modules": false }]
  ]
}
```
while also advising users to abandon it.

@kdex After a week of testing I'm fairly confident that the replacement implementation is producing exactly the same results as the old way did and as such there should not be any differences being experianced by the end user.

I will now close this issue but please feel free to reopen it should you still find a need to do so.
Cheers!

**Comment by kdex** [comment]
@Bartekus I've tested this, too. If your build pipeline doesn't contain any processes whose configurations need to be transpiled themselves, you're fine.

But as soon as you instruct babel not to transpile modules, such processes will fail, since `import` isn't natively supported by node yet.

Give it a try; disable module transpilation in your `.babelrc` and watch your ES2015+ gulpfiles or ES2015+ webpack configuration files break.

**Comment by amir20** [comment]
@kdex I had the same problem with my tests via `jest`. I was able to get it to work by changing the configuration for env=test. 
.babelrc
```json
{
  "presets": [
    "react",
    ["es2015", {"modules": false}]
  ],
  "env": {
    "test": {
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  }
}
```
Maybe you can do something similar for gulp.

**Comment by tamlyn** [comment]
What about CLI usage? 

I want to compile both a version with plan ES5 and [one with ES5 + ES modules](https://github.com/rollup/rollup/wiki/pkg.module). It doesn't appear that you can pass options to a preset via the CLI interface (please say I'm wrong).

So the next best option is:

    babel-cli src/ --preset es2015 --out-dir dist/
    babel-cli src/ --preset es2015-native-modules --out-dir esm/
